const assert = require('assert');
const fs = require('fs');
const path = require('path');

// The app shipped for months declaring icons that were generated by an Express
// route: one handler answered /icon-N.svg and /icon-N.png with the same SVG
// document. Nothing failed. The manifest parsed, every URL returned 200, and
// the only symptom was that the app could not actually be installed — Safari
// ignores an SVG apple-touch-icon, and an installability check that fails is
// reported in devtools, not in a test run.
//
// So this asserts the contract from both ends: every icon the manifest and the
// markup promise exists on disk, and the ones that must be PNG really are PNG
// by their magic bytes rather than by their file extension.

const ROOT = path.join(__dirname, '..');
const PUBLIC = path.join(ROOT, 'src', 'public');
const MANIFEST = JSON.parse(fs.readFileSync(path.join(PUBLIC, 'manifest.json'), 'utf8'));
const HTML = fs.readFileSync(path.join(PUBLIC, 'index.html'), 'utf8');

const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47]);

/** Resolve a root-relative URL from the manifest to its file on disk. */
function asset(url) {
  return path.join(PUBLIC, url.replace(/^\//, ''));
}

function isPng(file) {
  const fd = fs.openSync(file, 'r');
  const head = Buffer.alloc(4);
  fs.readSync(fd, head, 0, 4, 0);
  fs.closeSync(fd);
  return head.equals(PNG_MAGIC);
}

describe('PWA install contract', function () {
  it('ships every icon the manifest declares', function () {
    assert.ok(MANIFEST.icons.length > 0, 'the manifest declares no icons');
    for (const icon of MANIFEST.icons) {
      const file = asset(icon.src);
      assert.ok(
        fs.existsSync(file),
        `${icon.src} is declared in manifest.json but does not exist.\n`
          + 'A missing icon does not fail to load loudly — the browser simply '
          + 'refuses to offer the install prompt.',
      );
      if (icon.type === 'image/png') {
        assert.ok(isPng(file), `${icon.src} is declared image/png but is not PNG data`);
      }
    }
  });

  it('offers the sizes and purposes an installable app needs', function () {
    const any = MANIFEST.icons.filter((i) => (i.purpose || 'any').split(' ').includes('any'));
    const maskable = MANIFEST.icons.filter((i) => (i.purpose || '').split(' ').includes('maskable'));

    const sizes = new Set(any.map((i) => i.sizes));
    assert.ok(sizes.has('192x192'), 'a 192x192 "any" icon is required to install');
    assert.ok(sizes.has('512x512'), 'a 512x512 "any" icon is required for the splash screen');

    assert.ok(maskable.length > 0, 'without a maskable icon Android crops the artwork');
    // The same file as both "any" and "maskable" is cropped on one platform and
    // padded into dead space on the other; they are separate artworks here.
    const anySrc = new Set(any.map((i) => i.src));
    for (const icon of maskable) {
      assert.ok(
        !anySrc.has(icon.src),
        `${icon.src} is declared both any and maskable; ship a padded variant instead`,
      );
    }
  });

  it('keeps the fields that decide whether the browser offers an install', function () {
    assert.ok(MANIFEST.name, 'name');
    assert.ok(MANIFEST.short_name, 'short_name');
    assert.ok(MANIFEST.start_url, 'start_url');
    assert.strictEqual(MANIFEST.display, 'standalone');
    assert.deepStrictEqual(
      MANIFEST.display_override,
      ['window-controls-overlay', 'standalone', 'minimal-ui', 'browser'],
      'WCO must be preferred while preserving progressively broader fallbacks',
    );
    assert.ok(/^#[0-9a-f]{6}$/i.test(MANIFEST.background_color), 'background_color');
    assert.ok(/^#[0-9a-f]{6}$/i.test(MANIFEST.theme_color), 'theme_color');
  });

  it('does not promise a screenshot it cannot serve', function () {
    // Chrome reads `screenshots` for the richer install dialog and complains
    // about entries it cannot fetch. The old manifest listed one that 404ed.
    for (const shot of MANIFEST.screenshots || []) {
      assert.ok(fs.existsSync(asset(shot.src)), `${shot.src} is declared but missing`);
    }
  });

  it('gives iOS a real PNG for the home-screen icon', function () {
    const match = HTML.match(/<link[^>]*rel="apple-touch-icon"[^>]*href="([^"]+)"/);
    assert.ok(match, 'index.html declares no apple-touch-icon');

    const file = asset(match[1]);
    assert.ok(fs.existsSync(file), `apple-touch-icon ${match[1]} does not exist`);
    assert.ok(
      isPng(file),
      `apple-touch-icon ${match[1]} is not PNG data. Safari silently ignores `
        + 'anything else, which leaves "Add to Home Screen" with a blank tile.',
    );
  });

  it('ships the favicon browsers request without being asked', function () {
    const ico = path.join(PUBLIC, 'favicon.ico');
    assert.ok(fs.existsSync(ico), 'favicon.ico is missing, so every page load 404s for it');

    const head = fs.readFileSync(ico).subarray(0, 4);
    assert.deepStrictEqual(
      [...head],
      [0, 0, 1, 0],
      'favicon.ico is not an ICO container',
    );
  });

  it('resolves every icon the markup links to', function () {
    const hrefs = [...HTML.matchAll(/<link[^>]*rel="(?:icon|apple-touch-icon)"[^>]*href="([^"]+)"/g)]
      .map((m) => m[1]);
    assert.ok(hrefs.length > 0, 'index.html links no icons at all');
    for (const href of hrefs) {
      assert.ok(fs.existsSync(asset(href)), `${href} is linked from index.html but missing`);
    }
  });
});
