import { constants as hostFsConstants } from 'fs';
import * as fs from 'fs/promises';
import * as path from 'path';
import {
  ASK_TOOL_DEFINITION,
  SUBMIT_PLAN_TOOL_DEFINITION,
  TIER_TOOL_DEFINITION,
} from './ask-mcp.js';
import {
  ASK_QUESTION_TOOL,
  SUBMIT_PLAN_TOOL,
  TIER_TOOL,
} from '../../shared/chat-events.js';
import { FILE_CALLBACK_GENERATED_CLIENT_SOURCE } from './file-callback.js';

export const FILE_CALLBACK_DIR_ENV = 'CCWEB_CALLBACK_DIR';
export const FILE_CALLBACK_TOKEN_ENV = 'CCWEB_CALLBACK_TOKEN';

function hostFdAccessPath(handle: fs.FileHandle): string {
  return process.platform === 'linux' ? `/proc/self/fd/${handle.fd}` : `/dev/fd/${handle.fd}`;
}

function sameInode(left: { dev: number; ino: number }, right: { dev: number; ino: number }): boolean {
  return left.dev === right.dev && left.ino === right.ino;
}

export function fileMcpConfig(
  serverScript: string,
  _directory: string,
  _token: string,
  nodePath: string,
  laddered = false,
): string {
  return JSON.stringify({
    mcpServers: {
      ccweb: {
        command: nodePath,
        args: [serverScript],
        // The runtime launch environment already carries CCWEB_CALLBACK_*.
        // Repeating the token here would expose it in Claude's --mcp-config
        // argv. MCP children inherit the launch environment; only the
        // non-secret per-server ladder flag needs an explicit override.
        ...(laddered ? { env: { CCWEB_TIER_LADDER: '1' } } : {}),
      },
    },
  });
}

/**
 * Write a self-contained MCP server where a remote runtime can see it.
 *
 * The installed server bundle is not mounted into remote Docker engines or
 * Kubernetes user pods. This small generated module uses only Node built-ins
 * and talks through the shared-home file callback instead.
 */
export async function writeFileMcpBridge(directory: string): Promise<string> {
  const target = path.join(directory, 'ccweb-mcp.mjs');
  const source = `// Generated by code-agents-webcli for one chat session.
import * as crypto from 'node:crypto';
import { constants as fsConstants } from 'node:fs';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { createInterface } from 'node:readline';

const DIRECTORY = process.env.${FILE_CALLBACK_DIR_ENV};
const TOKEN = process.env.${FILE_CALLBACK_TOKEN_ENV};
const ASK_ENABLED = process.env.CCWEB_QUESTION_TOOL_ENABLED === '1';
const TIERED = process.env.CCWEB_TIER_LADDER === '1';
const LIVENESS_MS = Number(process.env.CCWEB_CALLBACK_LIVENESS_MS) || 10000;
const ASK = ${JSON.stringify(ASK_TOOL_DEFINITION)};
const PLAN = ${JSON.stringify(SUBMIT_PLAN_TOOL_DEFINITION)};
const TIER = ${JSON.stringify(TIER_TOOL_DEFINITION)};

${FILE_CALLBACK_GENERATED_CLIENT_SOURCE}

async function request(kind, payload, signal) {
  if (!DIRECTORY || !TOKEN) throw new Error('this session has no channel to the browser');
  const layout = await callbackLayout(DIRECTORY);
  const id = crypto.randomBytes(16).toString('base64url');
  const requestFile = path.join(layout.requests.path, id + '.json');
  const replyFile = path.join(layout.replies.path, id + '.json');
  const cancelFile = path.join(layout.cancelled.path, id + '.cancel');
  const heartbeatFile = path.join(layout.replies.path, 'heartbeat.json');
  let lastHeartbeat = null;
  let lastHeartbeatChange = Date.now();
  let requestWritten = false;
  let succeeded = false;
  let nextLivenessCheck = Date.now() + LIVENESS_MS;
  try {
    const initialHeartbeat = await callbackRead(
      layout.replies, heartbeatFile, TOKEN, CALLBACK_AAD_PREFIX + 'heartbeat',
    );
    lastHeartbeat = typeof initialHeartbeat?.ts === 'number' ? initialHeartbeat.ts : null;
    requestWritten = true;
    await callbackAtomic(
      layout.requests,
      requestFile,
      TOKEN,
      callbackAad('request', id),
      { id, kind, payload, createdAt: Date.now() },
    );
    while (true) {
      if (signal?.aborted) throw new Error('the agent stopped waiting for an answer');
      const reply = await callbackRead(layout.replies, replyFile, TOKEN, callbackAad('reply', id));
      if (reply) {
        if (reply.id !== id) throw new Error('the callback returned an invalid reply');
        if (reply.cancelled) throw new Error('the agent stopped waiting for an answer');
        if (reply.error) throw new Error(reply.error);
        succeeded = true;
        return reply.result;
      }
      if (Date.now() >= nextLivenessCheck) {
        const heartbeat = await callbackRead(
          layout.replies, heartbeatFile, TOKEN, CALLBACK_AAD_PREFIX + 'heartbeat',
        );
        if (!heartbeat || typeof heartbeat.ts !== 'number') {
          throw new Error('the callback server is unavailable');
        }
        if (heartbeat.ts !== lastHeartbeat) {
          lastHeartbeat = heartbeat.ts;
          lastHeartbeatChange = Date.now();
        } else if (Date.now() - lastHeartbeatChange >= LIVENESS_MS) {
          throw new Error('the callback server is unavailable');
        }
        nextLivenessCheck = Date.now() + Math.min(2000, LIVENESS_MS);
      }
      await new Promise((resolve) => setTimeout(resolve, 200));
    }
  } finally {
    if (requestWritten && !succeeded) {
      await callbackAtomic(
        layout.cancelled,
        cancelFile,
        TOKEN,
        callbackAad('cancel', id),
        { id, cancelledAt: Date.now() },
      ).catch(() => {});
    }
    await callbackUnlink(layout.requests, requestFile).catch(() => {});
    await callbackUnlink(layout.replies, replyFile).catch(() => {});
  }
}

function answerText(answer) {
  if (answer?.error) return { text: 'The question could not be put to the user: ' + answer.error + '. Ask in plain prose instead.', isError: true };
  const labels = Array.isArray(answer?.labels) ? answer.labels.map(String) : [];
  const typed = typeof answer?.text === 'string' ? answer.text : '';
  if (answer?.skipped || (!labels.length && !typed)) return { text: 'The user skipped this question. Do not ask it again; choose a reasonable path or ask in prose if blocked.', isError: false };
  if (typed && !labels.length) return { text: 'The user answered in their own words: "' + typed + '".', isError: false };
  return { text: 'The user selected: ' + labels.map((label) => '"' + label + '"').join(', ') + (typed ? ' and added: "' + typed + '"' : ''), isError: false };
}

const calls = new Map();
const send = (message) => process.stdout.write(JSON.stringify(message) + '\\n');
const cancelCalls = () => {
  for (const controller of calls.values()) controller.abort();
  calls.clear();
};
let shuttingDown = false;
const cancelAndExit = () => {
  if (shuttingDown) return;
  shuttingDown = true;
  cancelCalls();
  // Aborted request loops write their cancellation marker in finally on the
  // next poll. The ceiling is teardown-only, never user think time.
  setTimeout(() => process.exit(0), 1000);
};
for (const signal of ['SIGTERM', 'SIGINT', 'SIGHUP']) process.once(signal, cancelAndExit);
const rpc = createInterface({ input: process.stdin });
rpc.on('close', cancelCalls);
rpc.on('line', (line) => {
  if (!line.trim()) return;
  let message;
  try { message = JSON.parse(line); } catch { return; }
  const { id, method, params } = message;
  if (method === 'initialize') {
    send({ jsonrpc: '2.0', id, result: { protocolVersion: params?.protocolVersion || '2025-06-18', capabilities: { tools: {} }, serverInfo: { name: 'ccweb', version: '1.0.0' } } });
    return;
  }
  if (method === 'tools/list') {
    send({ jsonrpc: '2.0', id, result: { tools: [...(ASK_ENABLED ? [ASK] : []), PLAN, ...(TIERED ? [TIER] : [])] } });
    return;
  }
  if (method === 'tools/call') {
    const controller = new AbortController();
    if (id !== undefined) calls.set(id, controller);
    const finish = () => { if (id !== undefined && calls.get(id) === controller) calls.delete(id); };
    if (params?.name === '${ASK_QUESTION_TOOL}' && ASK_ENABLED) {
      void request('question', params.arguments || {}, controller.signal).then((answer) => {
        if (controller.signal.aborted) return;
        const result = answerText(answer);
        send({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: result.text }], isError: result.isError } });
      }).catch((error) => {
        if (!controller.signal.aborted) send({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: 'The question could not reach the user: ' + error.message + '. Ask in prose instead.' }], isError: true } });
      }).finally(finish);
      return;
    }
    if (params?.name === '${SUBMIT_PLAN_TOOL}') {
      void request('plan', params.arguments || {}, controller.signal).then((result) => {
        if (!controller.signal.aborted) send({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: result?.detail || 'Plan submitted.' }], isError: result?.accepted !== true } });
      }).catch((error) => {
        if (!controller.signal.aborted) send({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: 'The plan could not reach the Web interface: ' + error.message + '. Return it as your final markdown reply instead.' }], isError: true } });
      }).finally(finish);
      return;
    }
    if (params?.name === '${TIER_TOOL}' && TIERED) {
      void request('tier', params.arguments || {}, controller.signal).then((result) => {
        if (!controller.signal.aborted) send({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: result?.detail || 'The tier request was refused.' }], isError: false } });
      }).catch((error) => {
        if (!controller.signal.aborted) send({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: error.message }], isError: false } });
      }).finally(finish);
      return;
    }
    finish();
    send({ jsonrpc: '2.0', id, error: { code: -32601, message: 'no tool named ' + String(params?.name) } });
    return;
  }
  if (method === 'notifications/cancelled') {
    calls.get(params?.requestId)?.abort();
    calls.delete(params?.requestId);
    return;
  }
  if (id !== undefined) send({ jsonrpc: '2.0', id, result: {} });
});
`;
  const opened = await fs.open(
    directory,
    hostFsConstants.O_RDONLY | hostFsConstants.O_DIRECTORY | hostFsConstants.O_NOFOLLOW,
  );
  try {
    const endpointStat = await opened.stat();
    if (!endpointStat.isDirectory()) throw new Error('unsafe file callback endpoint');
    const accessPath = hostFdAccessPath(opened);
    const anchoredStat = await fs.stat(accessPath).catch(() => null);
    if (!anchoredStat || !anchoredStat.isDirectory() || !sameInode(endpointStat, anchoredStat)) {
      throw new Error('file callback fd access is unavailable');
    }
    for (const folder of ['requests', 'replies', 'cancelled']) {
      const child = await fs.open(
        path.join(accessPath, folder),
        hostFsConstants.O_RDONLY | hostFsConstants.O_DIRECTORY | hostFsConstants.O_NOFOLLOW,
      );
      try {
        const stat = await child.stat();
        if (!stat.isDirectory()) throw new Error(`unsafe file callback ${folder} directory`);
      } finally {
        await child.close();
      }
    }
    let artifact;
    let sealEndpoint = true;
    const anchoredTarget = path.join(accessPath, path.basename(target));
    try {
      artifact = await fs.open(
        anchoredTarget,
        hostFsConstants.O_WRONLY | hostFsConstants.O_NOFOLLOW,
      );
    } catch (error: unknown) {
      // Standalone callers (notably the bridge harness) may provide their own
      // safe directory rather than one created by FileCallbackBroker.
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
      sealEndpoint = false;
      await fs.writeFile(anchoredTarget, '', { encoding: 'utf8', flag: 'wx', mode: 0o600 });
      artifact = await fs.open(
        anchoredTarget,
        hostFsConstants.O_WRONLY | hostFsConstants.O_NOFOLLOW,
      );
    }
    try {
      const artifactStat = await artifact.stat();
      if (!artifactStat.isFile() || artifactStat.nlink !== 1) {
        throw new Error('unsafe file callback bridge artifact');
      }
      await artifact.truncate(0);
      await artifact.writeFile(source, { encoding: 'utf8' });
      await artifact.chmod(0o600);
      await artifact.sync();
    } finally {
      await artifact.close();
    }
    const visible = await fs.open(
      directory,
      hostFsConstants.O_RDONLY | hostFsConstants.O_DIRECTORY | hostFsConstants.O_NOFOLLOW,
    ).catch(() => null);
    if (!visible) throw new Error('file callback endpoint changed while installing its bridge');
    try {
      const current = await visible.stat();
      if (!sameInode(current, endpointStat)) {
        throw new Error('file callback endpoint changed while installing its bridge');
      }
    } finally {
      await visible.close();
    }
    // No later artifact needs a new entry in this directory. Existing request,
    // reply, cancellation, and pre-created .pi/ccweb directories remain usable,
    // while their names can no longer be replaced through the endpoint parent.
    if (sealEndpoint) await opened.chmod(0o500);
  } finally {
    await opened.close();
  }
  return target;
}
