import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { MODEL_TIERS, ModelTier, RuntimeProfile } from '../../shared/runtime-profiles.js';

/**
 * Write-through for capability tiers.
 *
 * Tiers are an abstraction this app owns; every runtime expresses them
 * differently, so each supported one gets a writer that renders the same four
 * strings into that CLI's native format. Runtimes with no delegation concept
 * simply have no writer, and the Settings UI says so rather than silently
 * accepting values that go nowhere.
 *
 * Two rules keep this from being destructive:
 *
 *  1. Generated files carry a marker line. A file without it was written by the
 *     user, and is never overwritten — the write is skipped and reported.
 *  2. Nothing is ever deleted. Switching profiles rewrites our files; it does
 *     not clean up, because "clean up" and "delete the user's agent" are the
 *     same operation from the filesystem's point of view.
 */
export const MANAGED_MARKER = 'managed-by: code-agents-webcli';

export interface TierWriteResult {
  /** Files written or rewritten. */
  written: string[];
  /** Files left alone because the user owns them, with the reason. */
  skipped: { file: string; reason: string }[];
  /** Extra CLI arguments the runtime needs in order to pick the config up. */
  args: string[];
  /** Set when the runtime has no tier concept at all. */
  unsupported?: boolean;
  /**
   * Set when nothing was written because the destination is only known once a
   * session starts. Carries the sentence to show instead of an empty report.
   */
  deferred?: string;
}

export interface TierWriterContext {
  /** Where generated, app-owned config files live. */
  generatedDir: string;
  homeDir: string;
  /**
   * The session's working directory, when one is known.
   *
   * Absent while previewing a save from Settings, where no session exists yet.
   * A writer that can only place its files per-session says so instead of
   * writing (see `deferred`).
   */
  workingDir?: string;
}

type Writer = (
  tiers: Partial<Record<ModelTier, string>>,
  profile: RuntimeProfile,
  ctx: TierWriterContext,
) => TierWriteResult;

/** Reasoning effort per tier. Cheap tiers think less; that is most of the saving. */
const TIER_EFFORT: Record<ModelTier, string> = {
  floor: 'low',
  mid: 'medium',
  high: 'high',
  top: 'max',
};

const TIER_DESCRIPTION: Record<ModelTier, string> = {
  floor:
    'Floor tier - high-volume, low-judgment, read-only work: codebase mapping, ' +
    'large searches, scanning verbose output, summarizing noisy results.',
  mid:
    'Mid tier - the standard coding model: standard implementation, most ' +
    'refactors, test writing, straightforward debugging.',
  high:
    'High tier - a strong reasoning model: tricky debugging, security-sensitive ' +
    'logic, cross-cutting implementation, adversarial review.',
  top:
    'Top tier - the most capable model, for the hardest work only: ambiguous ' +
    'architecture, high-stakes design, review of critical logic.',
};

/** Read-only tiers get a restricted toolset; the mid tier needs to edit. */
const TIER_TOOLS: Partial<Record<ModelTier, string>> = {
  floor: 'read, bash',
  top: 'read, bash',
};

function isManaged(file: string): boolean {
  try {
    return fs.readFileSync(file, 'utf8').includes(MANAGED_MARKER);
  } catch {
    return false;
  }
}

/** Write only if we own the target. Returns whether the write happened. */
function writeIfOurs(file: string, contents: string, result: TierWriteResult): void {
  if (fs.existsSync(file) && !isManaged(file)) {
    // The reason has to carry the *consequence*, not just the fact. "Not
    // generated by this app" reads as an internal detail; what the user needs
    // to know is that their file still wins, so this tier is doing nothing.
    result.skipped.push({
      file,
      reason: 'you wrote this one, so it stands and this tier is not applied',
    });
    return;
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents, 'utf8');
  result.written.push(file);
}

/**
 * Marks the generated agent directory as build output, so a project the app
 * writes into does not grow untracked files in `git status`. Written with `wx`,
 * so a `.gitignore` the user put there first is never touched.
 */
const AGENTS_GITIGNORE = [
  '# Written by code-agents-webcli: capability-tier agents for this session.',
  '# Regenerated on every launch; nothing here is yours to keep.',
  '*',
  '',
].join('\n');

function ensureIgnored(dir: string): void {
  try {
    fs.writeFileSync(path.join(dir, '.gitignore'), AGENTS_GITIGNORE, { flag: 'wx' });
  } catch (error) {
    // EEXIST is the normal case after the first launch. Anything else is worth
    // knowing about, but never worth failing a session start over.
    if ((error as NodeJS.ErrnoException).code !== 'EEXIST') {
      console.warn('Could not mark the generated agents directory as ignored:', error);
    }
  }
}

/**
 * pi.
 *
 * Written into the *session's* `.pi/agents/`, not `~/.pi/agent/agents/`.
 *
 * pi resolves subagents from four directories and lets later ones win on name
 * conflicts: `~/.claude/agents`, then `~/.pi/agent/agents`, then the nearest
 * project `.claude/agents`, then the nearest project `.pi/agents` — which is
 * therefore the one place this app can define `floor`/`mid`/`high`/`top`
 * without touching anything of the user's. (Verified against pi-code's
 * `subagent/agents.ts`; the project search stops at the repository root.)
 *
 * This is an override, not a replacement, and the distinction is the whole
 * point: a hand-written ladder in `~/.pi/agent/agents` stays byte-for-byte
 * intact and keeps applying to every pi session run outside this app, while
 * agents the app does *not* define — a `planner`, a `reviewer` — still load
 * from there and remain available inside it. Writing to the home directory
 * instead, as this did, could only ever be "your ladder or ours".
 *
 * The model is written provider-qualified only if the user qualified it: pi
 * resolves a bare "vendor/model" by treating the part before the slash as a
 * provider name, but which prefix is correct depends entirely on how that
 * install is authenticated, so guessing would be worse than passing it through.
 */
const writePiTiers: Writer = (tiers, profile, ctx) => {
  const result: TierWriteResult = { written: [], skipped: [], args: [] };

  if (!ctx.workingDir) {
    // Saving from Settings: there is no session yet, so there is no directory
    // to write into. Say when it will happen rather than reporting nothing.
    result.deferred =
      'Applied per session: the tier agents are written into each session’s ' +
      'working directory when it starts, where they override the global ones by ' +
      'name. Nothing in ~/.pi/agent/agents is touched.';
    return result;
  }

  const dir = path.join(ctx.workingDir, '.pi', 'agents');
  fs.mkdirSync(dir, { recursive: true });
  ensureIgnored(dir);

  for (const tier of MODEL_TIERS) {
    const model = tiers[tier];
    if (!model) continue;

    const tools = TIER_TOOLS[tier];
    const frontmatter = [
      '---',
      `name: ${tier}`,
      // Quoted: descriptions contain colons, and an unquoted colon breaks the
      // YAML parse, which makes the agent vanish with no error at all.
      `description: ${JSON.stringify(TIER_DESCRIPTION[tier])}`,
      ...(tools ? [`tools: ${tools}`] : []),
      `model: ${model}`,
      `effort: ${TIER_EFFORT[tier]}`,
      `# ${MANAGED_MARKER} (profile: ${profile.name})`,
      '---',
      '',
      TIER_DESCRIPTION[tier],
      '',
      ...(tools
        ? [
            'You are read-only. Use bash for inspection only - searching, reading, ',
            'and git history. Do not edit, write, install, or commit.',
            '',
          ]
        : []),
      'Report what you found or changed, with concrete file:line references.',
      '',
    ].join('\n');

    writeIfOurs(path.join(dir, `${tier}.md`), frontmatter, result);
  }

  return result;
};

/**
 * Oh My Pi.
 *
 * omp has native model roles, so tiers map onto config rather than onto agent
 * files, and `--config` takes an overlay for a single run. That keeps the
 * user's own ~/.omp/agent/config.yml untouched.
 */
const writeOmpTiers: Writer = (tiers, profile, ctx) => {
  const result: TierWriteResult = { written: [], skipped: [], args: [] };

  // omp's roles are not a 1:1 match for the four tiers: `smol` is the cheap
  // helper, `task` runs delegated work, `slow` is the reasoning model. `plan`
  // and `designer` follow the tiers closest to their job.
  const roles: [string, string | undefined][] = [
    ['smol', tiers.floor],
    ['task', tiers.mid],
    ['designer', tiers.mid],
    ['slow', tiers.high ?? tiers.top],
    ['plan', tiers.top ?? tiers.high],
    ['default', tiers.mid ?? tiers.high],
  ];

  const lines = [
    `# ${MANAGED_MARKER} (profile: ${profile.name})`,
    '# Generated from the capability tiers configured in Settings.',
    '# Edits here are overwritten when the profile is saved.',
    'modelRoles:',
  ];
  let any = false;
  for (const [role, model] of roles) {
    if (!model) continue;
    // Quoted so a model id containing ':' (a thinking-level suffix, say) stays
    // one scalar instead of parsing as a nested mapping.
    lines.push(`  ${role}: ${JSON.stringify(model)}`);
    any = true;
  }
  if (!any) return result;

  const file = path.join(ctx.generatedDir, `omp-${profile.id}.yml`);
  writeIfOurs(file, `${lines.join('\n')}\n`, result);
  if (result.written.includes(file)) {
    result.args.push('--config', file);
  }
  return result;
};

const WRITERS: Record<string, Writer> = {
  pi: writePiTiers,
  omp: writeOmpTiers,
};


/** Whether tiers configured for this runtime will actually be applied. */
export function supportsTiers(runtime: string): boolean {
  return runtime in WRITERS;
}

export function tierCapableRuntimes(): string[] {
  return Object.keys(WRITERS);
}

/**
 * Render a profile's tiers into the runtime's native config.
 *
 * Returns the extra arguments the spawn needs, plus what was written and what
 * was deliberately left alone. Never throws: a failed write degrades to
 * "launched without tiers", which is recoverable, where a thrown error would
 * mean the user cannot start the runtime at all.
 */
export function applyTiers(
  profile: RuntimeProfile,
  ctx: TierWriterContext,
): TierWriteResult {
  const empty: TierWriteResult = { written: [], skipped: [], args: [] };
  if (!profile.tiers || Object.keys(profile.tiers).length === 0) return empty;

  const writer = WRITERS[profile.runtime];
  if (!writer) return { ...empty, unsupported: true };

  try {
    return writer(profile.tiers, profile, ctx);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`runtime profiles: could not write ${profile.runtime} tiers: ${message}`);
    return empty;
  }
}

export function defaultTierContext(dataDir: string): TierWriterContext {
  return {
    generatedDir: path.join(dataDir, 'runtime-profiles'),
    homeDir: os.homedir(),
  };
}
